### ISSUE TITLE
The Composer package manager could not be found

### ISSUE THREAD

**Issue by thasmo** [rocketeers/rocketeer#410] opened 2015-01-18 14:40 UTC
When running `rocketeer check -vvv` the following is output:
```shell
| Check (Check if the server is ready to receive the application) [~5.56s]
|-- Check/Php (Checks if the server is ready to receive a PHP application)
|=> Checking presence of git
$ git --version
[thasmo@example.com] (production) git version 1.8.2.1
|=> Checking presence of Composer
$ [ -e "/home/thasmo/example.com/current/composer.json" ] && echo "true"
|=> Checking PHP version
|=> Checking presence of required extensions
$ /package/host/localhost/php-5.5/bin/php -r="print defined('HHVM_VERSION') ? HHVM_VERSION : PHP_VERSION;"
$ /package/host/localhost/php-5.5/bin/php -m
[thasmo@example.com] (production) PHP Warning:  PHP Startup: Unable to load dynamic library '/home/thasmo/pecl/apc.so' - /home/thasmo/pecl/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/thasmo/pecl/memcache.so' - /home/thasmo/pecl/memcache.so: cannot open shared object file: No such file or directory in Unknown on line 0
[thasmo@example.com] (production) [PHP Modules]
[thasmo@example.com] (production) bcmath
calendar
Core
ctype
curl
[thasmo@example.com] (production) date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
[thasmo@example.com] (production) json
ldap
libxml
mbstring
mcrypt
mysql
mysqli
mysqlnd
openssl
pcntl
[thasmo@example.com] (production) pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
Reflection
[thasmo@example.com] (production) session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
[thasmo@example.com] (production) sysvshm
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib
[thasmo@example.com] (production) [Zend Modules]
|=> Checking presence of required drivers
The Composer package manager could not be found
The tasks queue was canceled by task "Check"
Execution time: 4.5499s
Saved logs to /cygdrive/s/Project/web/example.com/.rocketeer/logs/production--20150118.log
```
When logging in via SSH manually to the server `composer` is in the path and I can easily run it by typing `composer`.

Why can't rocketeer find Composer? Any idea?

**Comment by ShonM** [comment] 2015-01-19 14:38
I started getting this a few days ago after having not got it (and upgrading Rocketeer). Just wanted to +1, can give any info needed (but having the same issue).

**Comment by Anahkiasen** [comment] 2015-01-19 19:27
If you do `which composer` on your server what do you get?

**Comment by thasmo** [comment] 2015-01-19 21:53
`which composer` returns `~/bin/composer`.

**Comment by Anahkiasen** [comment] 2015-01-19 22:03
Well that's weirder then, and in paths.php you haven't set anything that might throw Composer off?

**Comment by thasmo** [comment] 2015-01-19 22:40
I've tried this:
```php
<?php

return array(
	'php' => 'php',
	'composer' => 'composer',
	'artisan' => 'artisan',
);
```
and this:
```php
<?php

return array(
	'php' => '',
	'composer' => '',
	'artisan' => '',
);
```

**Comment by Anahkiasen** [comment] 2015-01-21 19:59
Hm ok, do `rocketeer tinker` and then type `$ssh->which('composer')` see what Rocketeer's which returns? Is this Rocketeer 2.0 or 2.1-dev?

**Comment by thasmo** [comment] 2015-01-21 22:08
@Anahkiasen, it returns:
```php
PHP Fatal error:  Class 'Boris\Boris' not found in phar:///usr/local/bin/rocketeer/src/Rocketeer/Console/Commands/TinkerCommand.php on line 26

Fatal error: Class 'Boris\Boris' not found in phar:///usr/local/bin/rocketeer/src/Rocketeer/Console/Commands/TinkerCommand.php on line 26
```
It's version 2.0.4.

Also I'm on Windows, using Cygwin and I think Boris only runs on Linux/Mac.

**Comment by GrahamCampbell** [comment] 2015-01-21 22:12
> Also I'm on Windows, using Cygwin and I think Boris only runs on Linux/Mac.

Boris will still install on windows. Composer will just be retarded and give you and old version because the maintainer forgot to add extension requirements to it.

**Comment by thasmo** [comment] 2015-01-21 22:31
Sorry, I meant Rocketeer is version 2.0.4.

**Comment by thasmo** [comment] 2015-01-21 22:31
Boris seems to be missing in the phar file which I am using.

**Comment by Anahkiasen** [comment] 2015-01-22 09:35
Seems the PHAR didn't get compiled properly by the cron, will manually regenerate them

**Comment by errodr** [comment] 2015-01-25 19:31
Any update on this issue? I am getting the same errors re: Composer not found and Boris not found.

I am on Rocketeer v2.0.4

**Comment by Anahkiasen** [comment] 2015-01-25 20:26
Ok I fixed the issue in the PHAR recompilation, can you try with [the develop phar](http://rocketeer.autopergamene.eu/versions/rocketeer-develop.phar) see if the issue still occur then?

**Comment by thasmo** [comment] 2015-01-25 23:22
@Anahkiasen, this happens:
```
> rocketeer tinker
Psy Shell v0.3.3 (PHP 5.5.19 — cli) by Justin Hileman
>>> $ssh->which('composer')
=> "composer"
```
```
> rocketeer check
If a keyphrase is required, provide it
| Check (Check if the server is ready to receive the application) [~3.84s]
|-- Check/Php (Checks if the server is ready to receive a PHP application)
|=> Checking presence of git
$ git --version
[thasmo@thasmo.com] (production) git version 1.8.2.1
|=> Checking PHP version
|=> Checking presence of Composer
The Composer package manager could not be found
The tasks queue was canceled by task "Check"
Execution time: 3.4415s
Saved logs to /cygdrive/s/Project/web/thasmo.com/.rocketeer/logs/production--20150126.log
```

**Comment by Anahkiasen** [comment] 2015-01-25 23:32
What. In. The. Hell. Ok this is definitely not right, will try to reproduce this and see if I can come up with a fix.

**Comment by errodr** [comment] 2015-01-25 23:39
I get similar results:
vagrant@deploy:~/example_development$ rocketeer tinker

> Psy Shell v0.3.3 (PHP 5.5.9-1ubuntu4.5 — cli) by Justin Hileman
> $ssh->which('composer')
=> "/usr/local/bin/composer"
> exit
> Exit:  Goodbye.


> Check (Check if the server is ready to receive the application) [~0.53s]
>-- Check/Php (Checks if the server is ready to receive a PHP application)
> => Checking presence of svn
>$ svn --version
> [ericr@172.28.128.4] (production) svn, version 1.8.8 (r1568071)
> [ericr@172.28.128.4] (production) compiled Aug 13 2014, 17:12:39 on x86_64-> pc-linux-gnu
> [ericr@172.28.128.4] (production)
> [ericr@172.28.128.4] (production) Copyright (C) 2013 The Apache Software Foundation.
> This software consists of contributions made by many people;
> see the NOTICE file for more information.
> Subversion is open source software, see http://subversion.apache.org/
> [ericr@172.28.128.4] (production) The following repository access (RA) modules are available:

> * ra_svn : Module for accessing a repository using the svn network protocol.
>   - with Cyrus SASL authentication
>   - handles 'svn' scheme
> * ra_local : Module for accessing a repository on local disk.
>   - handles 'file' scheme
> * ra_serf : Module for accessing a repository via WebDAV protocol using serf.
>   - using serf 1.3.3
>   - handles 'http' scheme
>   - handles 'https' scheme
> |=> Checking PHP version
> |=> Checking presence of Composer
> The Composer package manager could not be found
> The tasks queue was canceled by task "Check"
> Execution time: 0.444s

**Comment by Anahkiasen** [comment] 2015-01-26 00:57
There's two reasons a Package Manager would fail the check:
- Rocketeer can't find the path to it
- Rocketeer didn't find any manifest for it, locally or on the server (composer.json)

Can you check which of the two failed the check by doing this:

```php
$ rocketeer tinker
Psy Shell v0.3.3 (PHP 5.6.4 — cli) by Justin Hileman
>>> $ssh->binary('composer')->hasManifest();
=> true
>>> $ssh->binary('composer')->getBinary();
=> "/usr/local/bin/composer"
```

**Comment by errodr** [comment] 2015-01-26 01:15
Hmmm... It seems that there is no manifest:

```
Pay Shell v0.3.3 (PHP 5.5.9-1ubuntu4.5 - cli) by Justin Hileman
>>> $ssh->binary('composer')->hasManifest();
=> false
```

Seems to be the problem. Can you tell me how to fix this or point me in the right direction?

**Comment by Anahkiasen** [comment] 2015-01-26 01:16
Does you application actually need Composer?

**Comment by errodr** [comment] 2015-01-26 01:17
No, I don't think so... How can I make it stop checking for it?

**Comment by Anahkiasen** [comment] 2015-01-26 01:25
You can just disable the PHP related checks by setting `'Check' => null` in 'strategies.php` – you wouldn't get much use of the checks anyway since everything Rocketeer knows and checks about your application it infers from what version/dependencies/extensions you require in the `composer.json` file. 

Note that that will only work with 2.1-dev, not on 2.0.4

**Comment by errodr** [comment] 2015-01-26 01:38
Thanks...

I am running:

```
Rocketeer version 2.1.0 (f865b2d6a32af2defaf1511e453d602d981fba8d)
```

I tried:

```
'check' => '',
```

in strategies.php. Here is the output of rocketeer setup:

```
vagrant@deploy:~/example_development$ rocketeer setup

No agent is set for [production], please provide one:
| Setup (Set up the remote server for deployment)
|-- Check (Check if the server is ready to receive the application)
|===> Checking presence of svn
$ svn --version
[ericr@172.28.128.4] (production) svn, version 1.8.8 (r1568071)
[ericr@172.28.128.4] (production) compiled Aug 13 2014, 17:12:39 on x86_64-pc-linux-gnu
[ericr@172.28.128.4] (production)
[ericr@172.28.128.4] (production) Copyright (C) 2013 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/
[ericr@172.28.128.4] (production) The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.3
  - handles 'http' scheme
  - handles 'https' scheme
PHP Catchable fatal error:  Argument 1 passed to Rocketeer\Tasks\Check::checkLanguages() must be an instance of Rocketeer\Abstracts\Strategies\AbstractCheckStrategy, null given in phar:///usr/local/bin/rocketeer/src/Rocketeer/Tasks/Check.php on line 120
```

Is there something else I need to do?

**Comment by Anahkiasen** [comment] 2015-01-26 01:46
Yeah no sorry, I just pushed that actually so the PHAR wasn't done rebuilding when you tested :p Download the PHAR again from http//rocketeer.autopergamene.eu/versions/rocketeer-develop.phar and it should work

**Comment by errodr** [comment] 2015-01-26 01:58
Yes! Thanks so much for your help.

**Comment by thasmo** [comment] 2015-01-26 21:23
@Anahkiasen, using the new phar file and disabling the check strategy worked for me too!

**Comment by Anahkiasen** [comment] 2015-01-26 22:59
Aight, closing then

**Closed by Anahkiasen** 2015-01-26 22:59 UTC
Labels: bugs/bug, bugs/unverified

**Comment by aftabnaveed** [comment] 2015-02-11 02:32
@Anahkiasen  sorry since issue is related to this thread, I am posting it here 

will this not be ported back to 2.0.4  ?  since you said that is the latest stable release, honestly I am kind of blocked here with that issue and can't move forward :)  I appreciate your response and patience.

**Comment by aftabnaveed** [comment] 2015-02-11 03:12
version 3.0.0 and and disabling check in strategies worked for me too! for now I will just use it for my test environment.

**Comment by vicdelfant** [comment] 2015-06-01 09:01
We're having this problem as well (in our case with a legacy project with no composer.json at all). The rocketeer-develop PHAR seems far from stable for production use and 2.1.2 doesn't seem to be able to handle an empty value for `check`.

Is there a hotfix for 2.1.x available or is there anything else we can do?

**Comment by rot26** [comment] 2015-09-22 05:48
I had similar behavior and a google search lead me here, but thanks to the `$ssh->binary('composer')->hasManifest();`, I realized that I needed a `composer.json` in my app's root directory (duh?).

```sh
$ rocketeer --version
Rocketeer version 2.1.2
$ rocketeer check
...
|=> Checking presence of Composer
The Composer package manager could not be found
The tasks queue was canceled by task "Check"
```


Simple solution, but maybe it will save someone else some time.

```sh
$ cd /path/to/app/root/dir
$ composer init
$ cat /path/to/app/root/dir/composer.json
...
```

```sh
$ rocketeer tinker
Psy Shell v0.3.3 (PHP 5.6.4 — cli) by Justin Hileman
>>> $ssh->binary('composer')->hasManifest();
=> true
>>> $ssh->binary('composer')->getBinary();
=> "/usr/local/bin/composer"
```


Maybe there is a way to add a more descriptive solution when the check task fails with composer?
